CREATE TABLE ROOM (
    ID NUMBER,
    CONSTRAINT ROOM_ID PRIMARY KEY (ID),
    NUMBER_OF_GUETS NUMBER,
    PRICE FLOAT,
    BREAKFAST_INCLUDED NUMBER CHECK (BREAKFAST_INCLUDED = 0 OR BREAKFAST_INCLUDED = 1),
    PETS_ALLOWED NUMBER CHECK (PETS_ALLOWED = 0 OR PETS_ALLOWED = 1),
    DATE_AVAILABLE_FROM DATE,
    HOTEL_ID NUMBER,
    CONSTRAINT HOTEL_FK FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL (ID)
)