CREATE TABLE ORDERS (
    ID NUMBER,
    CONSTRAINT ORDER_ID PRIMARY KEY (ID),
    USER_ORDERED NUMBER, 
    CONSTRAINT USER_FK FOREIGN KEY (USER_ORDERED) REFERENCES USERS (ID),
    ROOM_ID NUMBER,
    CONSTRAINT ROOM_FK FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ID),
    DATE_FROM DATE,
    DATE_TO DATE,
    MONEY_PAID FLOAT
)