CREATE TABLE USERS(
    ID NUMBER,
    CONSTRAINT USER_ID PRIMARY KEY(ID),
    USER_NAME NVARCHAR2(30),
    PASSWORD NVARCHAR2(30),
    COUNTRY NVARCHAR2(30),
    USER_TYPE NVARCHAR2 (30) CHECK (USER_TYPE = 'ADMIN' OR USER_TYPE = 'USER')
)